package com.pet.wiseapp.db.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pet.wiseapp.db.model.AphorismModel;

import com.pet.wiseapp.db.model.AphorismModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aphorismModelDaoConfig;

    private final AphorismModelDao aphorismModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aphorismModelDaoConfig = daoConfigMap.get(AphorismModelDao.class).clone();
        aphorismModelDaoConfig.initIdentityScope(type);

        aphorismModelDao = new AphorismModelDao(aphorismModelDaoConfig, this);

        registerDao(AphorismModel.class, aphorismModelDao);
    }
    
    public void clear() {
        aphorismModelDaoConfig.clearIdentityScope();
    }

    public AphorismModelDao getAphorismModelDao() {
        return aphorismModelDao;
    }

}
